
name: 코웨이 프로모션 자동 스크래핑

on:
  schedule:
    - cron: '0 0,3,6,9,12,15,18,21 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4
      
    - name: Node.js 설정
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: 의존성 설치
      run: npm install puppeteer cheerio axios
        
    - name: 스크래핑 실행
      run: node scraper.js
      
    - name: 변경사항 커밋
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "프로모션 데이터 업데이트" || exit 0
        git push
